# ----
# Site

title: ZooNavigator Docs
url: "https://www.elkozmon.com"
baseurl: "/zoonavigator"
google_analytics_key: "UA-32389312-9"
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Web-based browser & editor for ZooKeeper.
author:
  name: Lubos Kozmon
  email: lubosh91@gmail.com
  twitter: # twitter username without the @ symbol
social:
  name: GitHub
  links:
    - https://github.com/elkozmon/zoonavigator

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - patch
  - minor
  - major
